# Generated by Django 4.0.2 on 2022-03-10 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stogram', '0002_profile_photo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouritePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_photo_photo', to='stogram.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_photo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite',
            },
        ),
    ]
