# Generated by Django 4.0.2 on 2022-03-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stogram', '0004_rename_photo_userfavouritephoto_favourite_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouritephoto',
            name='favourite_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_photo', to='stogram.photo'),
        ),
    ]
