# Generated by Django 4.0.2 on 2022-03-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stogram', '0005_alter_userfavouritephoto_favourite_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavouritephoto',
            old_name='user',
            new_name='favourite_photo_user',
        ),
    ]
