# Generated by Django 4.0.2 on 2022-03-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stogram', '0006_rename_user_userfavouritephoto_favourite_photo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavouritephoto',
            old_name='favourite_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='userfavouritephoto',
            old_name='favourite_photo_user',
            new_name='user',
        ),
    ]
